### PR TITLE
Makes the views implement AnimatedView interface to use polymorphism

### PR DESCRIPTION
**Pull request by marinomeneghel**

### CODE REVIEW

**Comment by ghost** [comment]
Hi, can it be adapted to a download ? Please

**Comment by marinomeneghel** [comment]
Hi msay2, what do you mean exactly?

**Comment by ghost** [comment]
so then I wanted to know if it was possible to adapt to a `DownloadManager`
(for `DownloadManager` i use a `AsyncTask`)

exactly like a `ProgressBar` ?

**Comment by marinomeneghel** [comment]
I still don't get your point, maybe because I don't know DownloadManager API. Do you want to 'adapt' the whole LoadingView to be used as you use a DownloadManager?

**Comment by marinomeneghel** [comment]
Closing as pretty old and the request for changes was not clarified

**Pull request closed without merging**
